sudo: required
services:
  - docker

before_install:
  - docker build -t test-container -f Dockerfile.dev .

script:
  - docker run --env CI=true test-container npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-276300688993"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECREATE_KEY"
